### ISSUE TITLE
Add New Flies - UI

### ISSUE THREAD

**Issue by rachael-t** [my-fly-box/my-fly-box-ui#1]
As a user, I can click an add button to add a new fly to my fly box.

- [x] [Button to Add Fly Page](#15)
- [x] [Add Fly Input Fields](#14)
- [x] [Clear Input Fields Button](#13)
- [x] [Submit New Fly Button](#12)
