### ISSUE TITLE
Edit Fly Information - UI

### ISSUE THREAD

**Issue by rachael-t** [my-fly-box/my-fly-box-ui#2]
As a user, I should be able to edit different input fields for a selected fly and save those updates

- [x] [Edit Flies Button](https://github.com/my-fly-box/my-fly-box-ui/issues/8)

- [x] [Input Fields to Edit Fly Data](https://github.com/my-fly-box/my-fly-box-ui/issues/9)

- [x] [Cancel Button for Editing Fly](https://github.com/my-fly-box/my-fly-box-ui/issues/10)

- [x] [Update Button](https://github.com/my-fly-box/my-fly-box-ui/issues/11)
