### ISSUE TITLE
User's Fly Box - UI

### ISSUE THREAD

**Issue by rachael-t** [my-fly-box/my-fly-box-ui#34]
Happy Path:
As a user, when I load the app, I should see the home page which is my "fly box" and displays all flies I have saved.

Sad Path:
As a user, when I load the app, I should see the home page which is my "fly box" and displays a message telling me to add flies if none are found. 

- [x] [Create Fly Box Page](https://github.com/my-fly-box/my-fly-box-ui/issues/35)

- [x] [Create API request for user's flies](https://github.com/my-fly-box/my-fly-box-ui/issues/36)

- [x] [Load flies onto page](https://github.com/my-fly-box/my-fly-box-ui/issues/37)

- [x] [Display message if no flies found](https://github.com/my-fly-box/my-fly-box-ui/issues/38)
