### ISSUE TITLE
Edit Fish Caught - UI

### ISSUE THREAD

**Issue by rachael-t** [my-fly-box/my-fly-box-ui#6]
As a User, a User can edit information on the fish that they had caught

- [x] [Should have labels and Input Fields](#20)
- [x] [Should have pre-filled Fish Information](#22)
- [x] [Cancel Button to cancel editing Fish](#23)
- [x] [Update Button to update Fish Information](#24)
