### ISSUE TITLE
Add New Fish - UI

### ISSUE THREAD

**Issue by rachael-t** [my-fly-box/my-fly-box-ui#7]
- [x] [Add new fish button](https://github.com/my-fly-box/my-fly-box-ui/issues/26)

- [x] [Add Fish Input Fields](https://github.com/my-fly-box/my-fly-box-ui/issues/52)

- [x] [Save new fish button](https://github.com/my-fly-box/my-fly-box-ui/issues/28)
